#!/bin/zsh
## Preview is tough and requires lots of escaping
HOMEBREW_NO_ENV_HINTS=true
local preview='brew info --json=v1 {} | jq -r ".[] | \"
Name: \(.name)
Tap: \(.tap)
Description: \(.desc)
License: \(.license)
Homepage: \(.homepage)
Version: \(.versions.stable)
Dependencies: \(.dependencies | join(\", \"))\n\""'

local installs=$(brew formulae | fzf -m \
  --ansi                 \
  --preview "${preview}" \
  --preview-window=:wrap \
  --min-height=17 | xargs )
# If nothing selected just exit

# Batch install and dump new Brewfile bundle
if [[ $installs ]]; then
  echo $installs | xargs brew install
  bupdate
fi

