#!/bin/zsh

##? pods - TODO: add description here
##?
##? usage: pods [-h|--help]
##?        pods [<options>] <arguments>

#function pods {

local -a o_help command
zmodload zsh/zutil
zparseopts -D -F -K --   {h,-help}=o_help ||
  return 1

if (( $#o_help )); then
  funchelp "pods"
  return
fi

#pods() {
command="kubectl get pods --all-namespaces"
  kubectl get pods -A | fzf --info=inline --layout=reverse --header-lines=1 \
  --prompt "$(kubectl config current-context | sed 's/-context$//')> " \
  --header $'╱ Enter (kubectl exec) ╱ CTRL-O (open log in editor) ╱ CTRL-R (reload) ╱\n\n' \
  --bind 'ctrl-/:change-preview-window(80%,border-bottom|hidden|)' \
  --bind 'enter:execute:kubectl exec -it --namespace {1} {2} -- sh > /dev/tty' \
  --bind 'ctrl-o:execute:${EDITOR:-vim} <(kubectl logs --all-containers --namespace {1} {2}) > /dev/tty' \
  --preview 'kubectl logs --follow --all-containers --tail=10000 --namespace {1} {2}' "$@"
  # --bind 'start:reload:$command' \
  # --bind 'ctrl-r:reload:$command' \
  # --preview-window up:follow \
#}

