#!/bin/zsh

##? pods: select one or more pods from all namespaces in current context
##?
##? usage: pods [-h|--help]
##?
##?   when running:
##?        pods [^e ] opens current pod in editor
##?        pods [^s ] opens a shel current pod (if it contains one)

#function pods {

local -a o_help command
zmodload zsh/zutil
zparseopts -D -F -K --   {h,-help}=o_help ||
  return 1

if (( $#o_help )); then
  funchelp "pods"
  return
fi

#pods() {
command="kubectl get pods --all-namespaces -o wide"
  kubectl get pods -A -o wide | fzf -m --info=inline --layout=reverse --header-lines=1 \
  --tiebreak=chunk,begin,length,index \
  --prompt 'Loading> ' --bind 'load:change-prompt:> ' \
  --header $'| CTRL-E Edit ╱ CTRL-S Shell(?) |\n\n' \
  --bind 'enter:become:(echo {+2})' \
  --bind 'ctrl-/:toggle-preview' \
  --bind 'alt-l:toggle-preview' \
  --bind 'ctrl-e:become:kubectl edit pod --namespace {1} {2}' \
  --bind 'ctrl-s:become:kubectl exec -it --namespace {1} {2} -- sh > /dev/tty' \
  --preview 'kubectl logs --follow --all-containers --tail=10000 --namespace {1} {2}' "$@" \
  --preview-window bottom:25%:follow:hidden \
  # --bind backward-eof:abort \
  # --bind 'start:reload:$command' \
  # --bind 'ctrl-r:reload:$command' \
#}

