-- Added for by recommendation: https://github.com/someone-stole-my-name/yaml-companion.nvim/issues/44
-- https://github.com/LazyVim/LazyVim/pull/2907#issuecomment-2150180952 closed due to schemastore being installed
-- this may no longer be necessary
return {
  --   "nvim-lualine/lualine.nvim",
  --   event = "VeryLazy",
  --   opts = function(_, opts)
  --     table.insert(opts.sections.lualine_z, {
  --       function()
  --         local schema = require("yaml-companion").get_buf_schema(0)
  --         if schema.result[1].name == "none" then
  --           return ""
  --         end
  --         return schema.result[1].name
  --       end,
  --       function()
  --         return " " .. os.date("%R")
  --       end,
  --     })
  --   end,
  --   {
  --     "someone-stole-my-name/yaml-companion.nvim",
  --     ft = { "yaml" },
  --     dependencies = {
  --       { "neovim/nvim-lspconfig" },
  --       { "nvim-lua/plenary.nvim" },
  --       { "nvim-telescope/telescope.nvim" },
  --     },
  --     config = function(_, opts)
  --       local cfg = require("yaml-companion").setup(opts)
  --       require("lspconfig")["yamlls"].setup(cfg)
  --       require("telescope").load_extension("yaml_schema")
  --     end,
  --   },
}
